server:
  port: 10010

# thymeleaf
spring:
  thymeleaf:
    mode: HTML5 # 页面格式
    encoding: UTF-8 # 页面编码
    servlet:
      content-type: text/html
    cache: false # 开发时关闭缓存，不然无法看到实时页面
    prefix: classpath:/templates/ # 页面的路径
  mvc:
    static-path-pattern: /**
